Implementation/EHR_system/ehr/ehr/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from App_1 import views as view
from Doctor_App import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^patientHistory/', view.patientHistory, name='patientHistory'),
    url(r'^$', view.home, name='home'),
    url(r'^login/$', view.patientLogin, name='login'),
    url(r'^logout/$', view.patientLogout, name='logout'),
    url(r'^patientProfile/$', view.patient_profile, name='patient_profile'),
    # url(r'^signup/', view.signup, name='signup'),
    url(r'^signup/$', view.temp_Register, name='signup'),
    url(r'^ajax/validate_email/$', view.validate_email, name='validate_email'),
    url(r'^ajax/valid_email/$', view.valid_email, name='valid_email'),
    url(r'^test/$', view.test, name='test'),
    url(r'^patientHistory/$', view.patientHistory, name='patientHistory'),
    url(r'^patientDoctor/$', view.patientDoctor, name='patientDoctor'),
    url(r'^pharmacy/(?P<primary_key>[0-9]+)/$',view.pharmacyShowData ,name = 'pharmacyShowData'),
    url(r'^pharmacy/(?P<forPatient>[0-9]+)/(?P<forMedicine>[0-9]+)/$',view.pharmacySubmitPatientMedicine ,name = 'pharmacySubmitPatientMedicine')



]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Implementation/EHR_system/ehr/App_1/models.py
from django.db import models

# Create your models here.


# class admin(models.Model):
#     id = models.AutoField(primary_key=True)
#     email = models.EmailField(max_length=255)
#     password = models.CharField(max_length=255)

# class temp(models.Model):
#     temp = models.ForeignKey(admin, on_delete=models.CASCADE)
#     first_name = models.CharField(max_length=255)
#     last_name = models.CharField(max_length=255)

class manager(models.Model):
    id = models.AutoField(primary_key=True)
    email = models.EmailField(max_length=255)
    password = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    state = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=255)
    blocked = models.BooleanField(default=False)

    def __str__(self):
        return self.email

class temp_register(models.Model):
    id = models.AutoField(primary_key=True)
    email = models.EmailField(max_length=255)
    password = models.CharField(max_length=255)
    def __str__(self):
        return self.email

class user(models.Model):
    user_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    gender = models.IntegerField()
    country = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    street = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=100)
    home_phone_number = models.CharField(max_length=100)
    work_phone_number = models.CharField(max_length=100)
    Date_of_birth = models.DateField()
    marital_status = models.CharField(max_length=100)
    Child_num = models.CharField(max_length=100)
    email_1 = models.EmailField(max_length=100)
    email_2 = models.EmailField(max_length=100)
    Nationality = models.CharField(max_length=100)
    Profile_picture = models.ImageField()
    Job_name = models.CharField(max_length=100)
    Job_organization = models.CharField(max_length=100)
    Jop_place = models.CharField(max_length=100)
    Ssn = models.CharField(max_length=100)
    Ssn_id = models.CharField(max_length=100)
    New_Password = models.CharField(max_length=100)
    SSN_Picture = models.ImageField()
    User_type = models.IntegerField()
    Create_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.first_name


    def __str__(self):
        return self.first_name


class patient(models.Model):
    Patient = models.ForeignKey(user, on_delete=models.CASCADE)
    Emergency_contact = models.CharField(max_length=50)
    QR_code = models.CharField(max_length=500)
    Disability_status = models.BooleanField(default=False)
    Height = models.FloatField()
    weight = models.FloatField()
    Blood_type = models.CharField(max_length=500)
    Chronic_diseases = models.BooleanField(default=False)

    def __str__(self):
        return self.Emergency_contact


class hospital(models.Model):
    h_id = models.AutoField(primary_key=True)
    h_name = models.CharField(max_length=500)
    h_country = models.CharField(max_length=100)
    h_state = models.CharField(max_length=100)
    h_city = models.CharField(max_length=100)
    h_street = models.CharField(max_length=100)
    h_zipcode = models.CharField(max_length=50)
    h_phone_num = models.CharField(max_length=100)
    h_type = models.CharField(max_length=100)
    h_ownership = models.CharField(max_length=100)
    h_emergency_service = models.BooleanField()
    h_date = models.DateField(auto_now_add=True)
    email = models.EmailField(max_length=100)
    website = models.TextField()
    logo = models.TextField()
    internal_medicine = models.IntegerField()
    cardiology = models.IntegerField()
    endocrinology = models.IntegerField()
    hematology = models.IntegerField()
    nephrology = models.IntegerField()
    surgery = models.IntegerField()
    pediatric = models.IntegerField()
    obstertics_genacology = models.IntegerField()
    ophthalmologist = models.IntegerField()
    neurology = models.IntegerField()
    Ear_nose_threat = models.IntegerField()
    urology = models.IntegerField()
    dermatology = models.IntegerField()
    hepatology = models.IntegerField()
    Radiology = models.IntegerField()
    psychiatry = models.IntegerField()
    dentistry = models.IntegerField()
    forensic_medicine = models.IntegerField()
    enatony = models.IntegerField()
    num_of_bed = models.IntegerField()
    hr_username = models.CharField(max_length=250)
    hr_password = models.CharField(max_length=250)
    creation_date = models.DateField()
    hos_rate = models.IntegerField()

    def __str__(self):
        return self.email


class organization(models.Model):
    org_id = models.AutoField(primary_key=True)
    org_name = models.CharField(max_length=250)
    org_country = models.CharField(max_length=100)
    org_state = models.CharField(max_length=100)
    org_city = models.CharField(max_length=100)
    org_zipcode = models.CharField(max_length=100)
    org_phone_num = models.CharField(max_length=50)
    org_email = models.EmailField(max_length=100)
    org_website = models.TextField()
    org_logo = models.TextField()
    hr_username = models.CharField(max_length=100)
    hr_password = models.CharField(max_length=100)
    creation_date = models.DateField(auto_now_add=True)
    org_rate = models.IntegerField()
    # 1 for lab
    # 2 for pharmacy
    # 3 for hospital
    Type = models.IntegerField()
    hospital = models.ForeignKey(hospital, blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.org_email


class doctor(models.Model):
    Doc = models.ForeignKey(user, on_delete=models.CASCADE)
    Registration_num = models.CharField(max_length=50)
    Specialization = models.CharField(max_length=100)
    Registration_date = models.DateTimeField(auto_now_add=True)
    licence = models.CharField(max_length=250)
    Last_date_payment = models.DateField(auto_now=True)
    End_date = models.DateField(auto_now=True)
    Specialization_type = models.CharField(max_length=100)
    University = models.CharField(max_length=100)
    Work_place = models.CharField(max_length=100)
    Sub_syndicate = models.CharField(max_length=500)
    General_secretary = models.CharField(max_length=500)
    Working_till = models.TimeField(auto_now=True)
    Graduation_year = models.CharField(max_length=50)
    doc_rate = models.IntegerField()
    hospital = models.ForeignKey(hospital, blank=True, null=True, on_delete=models.CASCADE)
    clinic = models.ForeignKey(organization, blank=True, null=True, on_delete=models.CASCADE)
    def __str__(self):
        return self.Doc.first_name


class prescription(models.Model):
    prescription_id = models.AutoField(primary_key=True)
    Disease_name = models.CharField(max_length=100)
    Disease_level = models.CharField(max_length=100)
    Disease_disc = models.TextField()
    Doctor_signature = models.CharField(max_length=500)
    next_appointment = models.DateTimeField()


class report(models.Model):
    report = models.AutoField(primary_key=True)
    patient = models.ForeignKey(patient, on_delete=models.CASCADE)
    prescription = models.ForeignKey(prescription, on_delete=models.CASCADE)
    doctor = models.ForeignKey(doctor, on_delete=models.CASCADE)
    clinic = models.ForeignKey(organization, on_delete=models.CASCADE, blank=True, null=True)
    hospital = models.ForeignKey(hospital, on_delete=models.CASCADE, blank=True, null=True)
    Submit_date = models.DateTimeField(auto_now=False, auto_now_add=True)


class all_analytics(models.Model):
    analytics_id = models.AutoField(primary_key=True)
    analytics_name = models.CharField(max_length=250)


class all_chronic(models.Model):
    chronic_id = models.AutoField(primary_key=True)
    chronic_name = models.CharField(max_length=250)


class all_medicine(models.Model):
    medicine_id = models.AutoField(primary_key=True)
    medicine_name = models.CharField(max_length=250)


class all_rays(models.Model):
    ray_id = models.AutoField(primary_key=True)
    ray_name = models.CharField(max_length=250)


class patient_analytics(models.Model):
    P_A_id = models.AutoField(primary_key=True)
    pat = models.ForeignKey(patient, on_delete=models.CASCADE)
    analy = models.ForeignKey(all_analytics, on_delete=models.CASCADE)
    analytics_result = models.TextField()
    lab = models.ForeignKey(organization, on_delete=models.CASCADE)
    submit_analytics_date = models.DateTimeField()


class patient_chronic(models.Model):
    P_C_id = models.AutoField(primary_key=True)
    pat = models.ForeignKey(patient, on_delete=models.CASCADE)
    chr = models.ForeignKey(all_chronic, on_delete=models.CASCADE)


class patient_medicine(models.Model):
    P_M_id = models.AutoField(primary_key=True)
    pat = models.ForeignKey(patient, on_delete=models.CASCADE)
    med = models.ForeignKey(all_medicine, on_delete=models.CASCADE)
    number_of_potions = models.IntegerField()
    number_of_pills = models.IntegerField()
    medicine_submit = models.BooleanField(default=False)
    pharmacy = models.ForeignKey(organization, on_delete=models.CASCADE)
    submit_medicine_date = models.DateTimeField()

class patient_rays(models.Model):
    P_R_id = models.AutoField(primary_key=True)
    pat = models.ForeignKey(patient, on_delete=models.CASCADE)
    ray = models.ForeignKey(all_rays, on_delete=models.CASCADE)
    rays_result = models.TextField()

Implementation/EHR_system/ehr/templates/base.html
<!DOCTYPE html>
<html lang="en">
{# Make modifiable head elements #}
<head>
    {% include "header.html" %}
</head>
<body class="{% if request.get_full_path == '/patientHistory/' %} body_color
 {% else %}body
 {% endif %}">
<div>
    <div class="super_container">

    {# Navigation Menu #}
        {% include "navbar.html" %}

    {# The Document Body #}
        {# Login Body #}
            {% block login_content %}
            {% endblock login_content %}
        {# Login Body #}
            {% block signup_content %}
            {% endblock signup_content %}
        {# Profile body#}
            {% block patientProfile %}
            {% endblock patientProfile %}
        {# patientData body#}
            {% block patientData %}
            {% endblock patientData %}
        {# doctorHome body#}
            {% block doctorHome %}
            {% endblock doctorHome %}


            </div>

        {# All Patient History #}
            {% block patient_history_content %}
            {% endblock patient_history_content %}
        {# Home Body #}
            {% block home_content %}
            {% endblock home_content %}
        {# patientDoctor body#}
            {% block patientDoctor %}
            {% endblock patientDoctor %}
    {# The Footer #}
        {% include "footer.html" %}
    </div>
{% block javascript %}
{% endblock javascript %}
</body>
</html>

Implementation/EHR_system/ehr/templates/doctorHome.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block doctorHome %}
    <div class="container" style="padding-top:200px">
        <h2 style="text-align:center;color:#FFF;margin:20px 0px 30px 0px">Doctor Home</h2>

        <div class="container">
            <div class="row">
                <div class="col" style="border:solid 3px black;margin:3px ">
                    {% for i in data %}
                        <p style="color: black">{{ i }}</p>
                    {% endfor %}
                </div>
                <div class="col" style="border:solid 3px black;margin:3px">
                    bad
                </div>
                <div class="col" style="border:solid 3px black;margin:3px">
                    rank
                </div>
            </div>
            <div class="row" style="border:solid 3px black; text-align: center">
                <div class="col-sm-6">
                    <p>
                        kadkankdnalwdnmlakwmdlk
                    </p>
                </div>
                <div class="col-sm-6">
                    <p>
                        kadkankdnalwdnmlakwmdlk
                    </p>
                </div>
            </div>
            <div class="row" style="border:solid 3px black; margin-top:3px">
            <p style="color: black">
                mmkn n7ot API bygib a3lanat mn bra w m4 hn7tag nktb fiha ay code

            </p>
            </div>
        </div>
    </div>

{% endblock doctorHome %}

Implementation/EHR_system/ehr/templates/footer.html
{% load staticfiles %}
<div style="
    {% if request.get_full_path == '/patientProfile/' %}
        width:10px;height:175px
    {% else %}
        {% if request.get_full_path == '/patientProfile/?c=1' %}
            width:10px;height:175px
        {% endif %}
    {% endif %}"></div>
<footer class="footer">
    <div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="{% static 'images/footer.jpg' %}" data-speed="0.8"></div>
    <div class="footer_content">
        <div class="container">
            <div class="row">

                <!-- Footer About -->
                <div class="col-lg-3 footer_col">
                    <div class="footer_about">
                        <div class="logo">
                            <a href="#">health<span>+</span></a>
                        </div>
                        <div class="footer_about_text">Lorem ipsum dolor sit amet, lorem maximus consectetur adipiscing elit. Donec malesuada lorem maximus mauris.</div>
                        <div class="footer_social">
                            <ul class="d-flex flex-row align-items-center justify-content-start">
                                <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                            </ul>
                        </div>
                        <div class="copyright">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </div>
                    </div>
                </div>

                <!-- Footer Contact -->
                <div class="col-lg-5 footer_col">
                    <div class="footer_contact">
                        <div class="footer_contact_title">Quick Contact</div>
                        <div class="footer_contact_form_container">
                            <form action="#" class="footer_contact_form" id="footer_contact_form">
                                <div class="d-flex flex-xl-row flex-column align-items-center justify-content-between">
                                    <input type="text" class="footer_contact_input" placeholder="Name" required="required">
                                    <input type="email" class="footer_contact_input" placeholder="E-mail" required="required">
                                </div>
                                <textarea class="footer_contact_input footer_contact_textarea" placeholder="Message" required="required"></textarea>
                                <button class="footer_contact_button">send message</button>
                            </form>
                        </div>
                    </div>
                </div>

                <!-- Footer Hours -->
                <div class="col-lg-4 footer_col">
                    <div class="footer_hours">
                        <div class="footer_hours_title">Opening Hours</div>
                        <ul class="hours_list">
                            <li class="d-flex flex-row align-items-center justify-content-start">
                                <div>Monday – Thursday</div>
                                <div class="ml-auto">8.00 – 19.00</div>
                            </li>
                            <li class="d-flex flex-row align-items-center justify-content-start">
                                <div>Friday</div>
                                <div class="ml-auto">8.00 - 18.30</div>
                            </li>
                            <li class="d-flex flex-row align-items-center justify-content-start">
                                <div>Saturday</div>
                                <div class="ml-auto">9.30 – 17.00</div>
                            </li>
                            <li class="d-flex flex-row align-items-center justify-content-start">
                                <div>Sunday</div>
                                <div class="ml-auto">9.30 – 15.00</div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer_bar">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="footer_bar_content d-flex flex-sm-row flex-column align-items-lg-center align-items-start justify-content-start">
                        <nav class="footer_nav">
                            <ul class="d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-start">
                                <li class="active"><a href="index.html">Home</a></li>
                                <li><a href="about.html">About Us</a></li>
                                <li><a href="services.html">Services</a></li>
                                <li><a href="news.html">News</a></li>
                                <li><a href="contact.html">Contact</a></li>
                            </ul>
                        </nav>
                        <div class="footer_links">
                            <ul class="d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-start">
                                <li><a href="#">Help Desk</a></li>
                                <li><a href="#">Emergency Services</a></li>
                                <li><a href="#">Appointment</a></li>
                            </ul>
                        </div>
                        <div class="footer_phone ml-lg-auto">
                            <i class="fa fa-phone" aria-hidden="true"></i>
                            <span>+34 586 778 8892</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>


<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

<script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
<script src="{% static 'plugins/easing/easing.js' %}"></script>
<script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
<script src="{% static 'styles/bootstrap-3.3.7/dist/js/bootstrap.js' %}"></script>
<script src="{% static 'js/patientSignup.js' %}"></script>
<script src="{% static 'js/patientHistory.js' %}"></script>

Implementation/EHR_system/ehr/templates/header.html
{% load staticfiles %}

<title>{% block title %}EHR {% endblock title %} | Healthcare</title>

{% block head_meta %}
{% block head_meta_charset %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
{% endblock head_meta_charset %}
{% block head_meta_contentlanguage %}
<meta http-equiv="Content-Language" value="en-US" />
{% endblock head_meta_contentlanguage %}
{% block head_meta_viewport %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% endblock head_meta_viewport %}

{% endblock head_meta %}
{% block head_css %}
{% block head_css_site %}
<link rel="shortcut icon" href="{% static 'img/favicon1.png' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
<link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'styles/main_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/responsive.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
<link rel="stylesheet" href="{% static 'styles/bootstrap-3.3.7/dist/css/bootstrap.css' %}">
{% endblock head_css_site %}
{% block head_css_page %}{% endblock head_css_page %}
{% endblock head_css %}

Implementation/EHR_system/ehr/templates/patientIdentity.html
<h1>Patient Identity</h1>
<div>
    <img src="">
    <h4> {{ patientData.first_name}}</h4>


</div>

Implementation/EHR_system/ehr/templates/patientProfile.html
{% extends "base.html"%}
{% load staticfiles %}
{% block patientProfile%}

{% if request.GET.c == "1" %}
<script>
    alert('passwords not matched')
</script>
{% endif %}

<div style="width:10px;height:175px"></div>
<div class="container">
    <h2 style="text-align:center;color:#FFF;margin:20px 0px 30px 0px">Profile Information</h2>
    <div class="jumbotron" style="background-color:rgba(18,17,17,0.66)">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-3">
                    <div class="row">
                        <div style="width:200px;margin: auto">
                            <img src="{% static 'images/user.png' %}" alt="profile picture" class="img-thumbnail"/>
                        </div>
                    </div>
                    <div class="row">
                        {{ form1.Profile_picture }}
                        <label for="file1">Choose a file</label>
                    </div>
                    <div style="margin-top:45px"></div>
                    <div class="row">
                        <div style="width:200px;margin: auto">
                            <img src="{% static 'images/SSN.png' %}"  alt="SSN" class="img-thumbnail">
                        </div>
                    </div>
                    <div class="row">
                        {{ form1.SSN_Picture }}
                        <label for="file2">Upload SSN</label>
                    </div>
                </div>
                <div class="col-9">
                    <div class="form-row" style="margin-bottom:20px">
                        <div class="col">
                            {{ form1.first_name }}
                        </div>
                        <div class="col">
                            {{ form1.middle_name }}
                        </div>
                        <div class="col">
                            {{ form1.last_name }}
                        </div>
                    </div>
                    <div class="form-row" style="margin-bottom:20px">
                        <div class="col">
                            {{ form1.country }}
                        </div>
                        <div class="col">
                            {{ form1.state }}
                        </div>
                        <div class="col">
                            {{ form1.city }}
                        </div>
                        <div class="col">
                            {{ form1.street }}
                        </div>
                    </div>
                    <div class="form-row" style="margin-bottom:20px">
                        <div class="col">
                            {{ form1.zip_code }}
                        </div>
                        <div class="col">
                            {{ form1.phone_number }}
                        </div>
                        <div class="col">
                            {{ form1.home_phone_number }}
                        </div>
                        <div class="col">
                            {{ form1.work_phone_number }}
                        </div>
                    </div>
                    <div class="form-row" style="margin-bottom:20px">
                        <div class="col">
                            {{ form1.gender }}
                        </div>
                        <div class="col">
                            {{ form1.Date_of_birth }}
                        </div>
                        <div class="col">
                            {{ form1.marital_status}}
                        </div>
                        <div class="col">
                            {{ form1.Child_num }}
                        </div>
                    </div>
                    <div class="form-row" style="margin-bottom:20px">
                        <div class="col">
                            {{ form1.email_1 }}
                            <b id="warn" class="hide">
                                <i class="fa fa-warning" aria-hidden="true"></i>
                                email already exist
                            </b>
                        </div>
                        <div class="col">
                            {{ form1.email_2 }}
                        </div>
                    </div>
                    <div class="form-row" style="margin-bottom:20px">
                        <div class="col">
                            {{ form1.Nationality }}
                        </div>
                        <div class="col">
                            {{ form1.Job_name }}
                        </div>
                        <div class="col">
                            {{ form1.Job_organization }}
                        </div>
                        <div class="col">
                            {{ form1.Jop_place }}
                        </div>
                    </div>
                    <div class="form-row" style="margin-bottom:20px">
                        <div class="col-6">
                            {{ form1.Ssn }}
                        </div>
                        <div class="col">
                            {{ form1.New_Password }}
                            <b id="warn1" class="hide">
                                <i class="fa fa-warning" aria-hidden="true"></i>
                                not matched
                            </b>
                        </div>
                        <div class="col">
                            {{ form1.Confirm_Pass }}
                            <b id="warn2" class="hide">
                                <i class="fa fa-warning" aria-hidden="true"></i>
                                not matched
                            </b>
                        </div>
                        {{ form1.Ssn_id }}
                        {{ form1.User_type }}
                    </div>
                    <div class="form-row" style="margin-bottom:20px">
                        <div class="col">
                            {{ form2.Emergency_contact }}
                        </div>
                        <div class="col">
                            {{ form2.Height }}
                        </div>
                        <div class="col">
                            {{ form2.weight }}
                        </div>
                    </div>
                    <div class="form-row" style="margin-bottom:20px">
                        <div class="col">
                            {{ form2.Blood_type }}
                        </div>
                        <div class="col" style="text-align:center">
                            {{ form2.Disability_status }}
                            <label style="font-size:2em;color:#32c69a" for="id_Disability_status">Disability</label>
                        </div>
                        <div class="col" style="text-align:center">
                            {{ form2.Chronic_diseases }}
                            <label style="font-size:2em;color:#32c69a" for="id_Chronic_diseases">Chronic</label>
                        </div>
                        {{ form2.QR_code }}
                    </div>
                </div>

            </div>
            <div class="row">
                <button id="id_signup_submit" type="submit" style="width:20%;margin:auto" class="button home_button">Submit</button>
            </div>
            <!--<input type="submit" class="form-control" style="width:20%;margin:40px auto 0px auto" value="Submit">-->
        </form>
    </div>
</div>
{% endblock patientProfile%}

Implementation/EHR_system/ehr/templates/pharmacyShowData.html
<h1>testin</h1>
{{prescriptions}}