Implementation/EHR/ehr/doctor/urls.py
from django.conf.urls import url
from doctor import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'doctor'
urlpatterns = [
    url(r'^Home/$', views.Doctor, name='doctor'),
    url(r'^resetpassword/$', views.RestDoctorPassword,name='resetpassword'),
    url(r'^$',views.GetPatianTID , name='patiant_id'),
    url(r'^patiant/prescription/$',views.ReportListView.as_view() , name='prescriptionlist'),
    url(r'^doctorProfileView/(?P<pk>[-\w]+)/$',views.doctorProfileDetialView.as_view(), name='doctorProfileView'),
    url(r'^patiant/prescription/(?P<pk>[-\w]+)/$',views.PrescriptionDetialView.as_view() , name='prescriptiondetial'),
    url(r'^prescription/newcreate/$',views.prescriptionFormView.as_view(),name='presc_create'),
    url(r'^prescription/update/(?P<pk>[-\w]+)/$',views.prescriptionUpdate.as_view(),name='update'),

    url(r'^patiant/prescription/(?P<pk>[-\w]+)/medecines/$',views.Medicen_List.as_view(),name='medlist'),
    url(r'^patiant/prescription/medecines/(?P<pk>[-\w]+)/$',views.Medicin_DetialView.as_view(),name='meddital'),
    url(r'^patiant/prescription/medecines/update/(?P<pk>[-\w]+)/$' , views.Medicen_UPDATE.as_view(),name='medupdate'),
    url(r'^patiant/prescription/medecines/newcreate/(?P<pk>[-\w]+)/$',views.MedicenFormView.as_view(),name='newmed'),

    url(r'^patiant/prescription/(?P<pk>[-\w]+)/rays/$',views.rays_List.as_view(),name='rayslist'),
    url(r'^patiant/prescription/rays/(?P<pk>[-\w]+)/$',views.rays_DetialView.as_view(),name='raydetial'),
    url(r'^patiant/prescription/rays/update/(?P<pk>[-\w]+)/$' , views.rays_UPDATE.as_view(),name='raysupdate'),
    url(r'^patiant/prescription/rays/newcreate/(?P<pk>[-\w]+)/$',views.raysFormView.as_view(),name='newray'),

    url(r'^patiant/prescription/(?P<pk>[-\w]+)/analytics/$',views.analytics_List.as_view(),name='analyticslist'),
    url(r'^patiant/prescription/analytics/(?P<pk>[-\w]+)/$',views.analytics_DetialView.as_view(),name='analyticsdetial'),
    url(r'^patiant/prescription/analytics/update/(?P<pk>[-\w]+)/$' , views.analytics_UPDATE.as_view(),name='analyticssupdate'),
    url(r'^patiant/prescription/analytics/newcreate/(?P<pk>[-\w]+)/$',views.analyticsFormView.as_view(),name='newanalytics'),

    # url(r'^doctorProfileView/$', views.doctor_profile_view, name='doctor_profile_view'),
    # url(r'^doctorProfileView/(?P<docid>\w+)/$', views.doctor_profile_view,name='doctor_profile_view'),
    url(r'^QRScan/$', views.QRCodeScanView, name='QRCodeScanView'),
    # url(r'^medi/$', views.medi, name='medi'),
    url(r'^QRScan/$', views.QRCodeScanView, name='QRCodeScanView'),
    url(r'^api/charts/data/$', views.DoctorStatistics.as_view(),name="api-data"),
    url(r'^Statistics/$', views.StatView.as_view(),name="stat"),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Implementation/EHR/ehr/ehr/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from patient import views

urlpatterns = [
    url(r'^$', views.patientLogin, name='patientLogin'),
    url(r'^catalog/$', views.patientLogin, name='patientLogin'),
    url(r'^admin/', admin.site.urls),
    url(r'^doctor/', include('doctor.urls')),
    url(r'^patient/', include('patient.urls')),
    url(r'^hospital/', include('hospital.urls')),
    url(r'^clinic/', include('clinic.urls')),
    url(r'^predict/',include('predict_risk.urls')),
    path('pharmacy/', include('pharmacy.urls')),
    path('lab/', include('lab.urls')),
]

admin.site.site_header = "EHR ADMIN"
admin.site.site_title = "EHR ADMIN"
admin.site.index_title = "Welcome to EHR SYSTEM"

Implementation/EHR/ehr/lab/urls.py
from django.conf.urls import url
from django.urls import path
from lab import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'lab'

urlpatterns = [
    path('', views.labLogin, name='labLogin'),
    path('logout/', views.labLogout, name='labLogout'),
    path('labPatientLogin/', views.labPatientLogin, name='labPatientLogin'),
    path('labPatientLogin/Analytics/', views.AnalyticsListView, name='AnalyticsListView'),
    path('labPatientLogin/Rays/', views.RaysListView, name='RaysListView'),
    url(r'^labProfileView/(?P<labid>\w+)/$', views.lab_profile_view,name='lab_profile_view'),
    url(r'^QRScan/$', views.QRCodeScanView, name='QRCodeScanView'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Implementation/EHR/ehr/pharmacy/urls.py
from django.conf.urls import url
from django.urls import path
from pharmacy import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'pharmacy'

urlpatterns = [
    path('', views.pharmacyLogin, name='pharmacyLogin'),
    path('logout/', views.pharmacyLogout, name='pharmacyLogout'),
    path('pharmacyPatientLogin/', views.pharmacyPatientLogin, name='pharmacyPatientLogin'),
    path('pharmacyPatientLogin/medicines/',views.medicineListView, name = 'medicineListView'),
    url(r'^pharmacyProfileView/(?P<pharid>\w+)/$', views.pharmacy_profile_view, name='pharmacy_profile_view'),
    url(r'^QRScan/$', views.QRCodeScanView, name='QRCodeScanView'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Implementation/EHR/ehr/pharmacy/models.py
from django.db import models

# Create your models here.

Implementation/EHR/ehr/pharmacy/views.py
from django.http import HttpResponseRedirect, HttpResponseNotFound, HttpResponse
from django.shortcuts import render, get_object_or_404

from doctor.models import patient_medicine
from hospital.models import organization
from patient.models import patient, user, AllNotification
from patient.views import QRCodeScanner


def pharmacyLogin(request):
    if request.method == 'POST':
        pharmacyName = request.POST['pharm_name']
        pharmacyPass = request.POST['pharm_pass']
        pharmacyUserFound = organization.objects.filter(hr_username__exact=pharmacyName).exists()
        pharmacyPassFound = organization.objects.filter(hr_password__exact=pharmacyPass).exists()
        if pharmacyUserFound:
            if pharmacyPassFound:
                organ_id = organization.objects.filter(Type=1).filter(hr_password=pharmacyPass).get(
                    hr_username=pharmacyName).org_id
                request.session['pharmacy_id'] = organ_id
                request.session['type'] = 'pharmacy'
                return HttpResponseRedirect('pharmacyPatientLogin/')
            else:
                print('wrong pass')
                return HttpResponse("You entered wrong pass")
        else:
            print('phar not exist')
            return HttpResponseNotFound('<h1>Pharmacy not found</h1>')
    else:
        request.session['type'] = 'pharmacy'
        return render(request, 'pharmacyLogin.html', {})


def pharmacyLogout(request):
    if request.session['type'] == 'pharmacy':
        if 'pharmacy_id' in request.session:
            request.session.pop('pharmacy_id')
            print('SESSION FOUND')
        if 'pharmacy_id' not in request.session:
            print('SESSION DELETED')
    else:
        print('there is no lab entered')
    return HttpResponseRedirect('/pharmacy/')


def pharmacyPatientLogin(request):
    if 'pharmacy_id' in request.session:
        if request.method == 'POST':
            ssn_id = request.POST['pat_id']
            user_found = user.objects.filter(Ssn_id__exact=ssn_id).exists()
            if user_found:
                myUser = user.objects.get(Ssn_id=ssn_id)
                user_type = myUser.User_type
                if str(user_type) == "1":
                    u_id = user.objects.get(Ssn_id=ssn_id).user_id
                    request.session['patien_id'] = u_id
                    return HttpResponseRedirect('medicines/')
                else:
                    return HttpResponseRedirect('/pharmacy/pharmacyPatientLogin/?notify=not_patient')
            else:
                return HttpResponseRedirect('/pharmacy/pharmacyPatientLogin/?notify=not_user')
        else:
            if 'ssnID' not in request.session:
                return render(request, 'pharmacyIndex.html', {'ph_id': request.session['pharmacy_id'],'first_name':pharmacyName(request)})
            else:
                return render(request, 'pharmacyIndex.html',
                              {'ph_id': request.session['pharmacy_id'], 'SSNID': request.session['ssnID'],'first_name':pharmacyName(request)})
    else:
        return HttpResponseRedirect('/pharmacy/')


def QRCodeScanView(request):
    QRData = QRCodeScanner()
    if QRData:
        QRData = QRData.decode("UTF-8")
        request.session['ssnID'] = QRData
        return HttpResponseRedirect('/pharmacy/pharmacyPatientLogin/')
    else:
        return HttpResponseRedirect('/pharmacy/pharmacyPatientLogin/')


def medicineListView(request):
    if 'pharmacy_id' in request.session:
        pharmacy_id = request.session['pharmacy_id']
        if 'ssnID' in request.session:
            request.session.pop('ssnID')
        # user_id = request.session['patient_id']
        # print(user_id)
        patient_id = patient.objects.get(Patient_id=request.session['patien_id']).id
        # print(patient_id)
        patientFoundTrueAndFalse = patient_medicine.objects.filter(pat_id__exact=patient_id).exists()
        # print(patientFoundTrueAndFalse)
        if patientFoundTrueAndFalse:
            medicineFound = patient_medicine.objects.filter(pharmacy__isnull=True).exists()
            if medicineFound:
                medicineData = patient_medicine.objects.filter(pharmacy__isnull=True)
                if request.method == 'POST':
                    medicineInsert = patient_medicine(P_M_id=request.POST['med_id'])
                    # print(medicineData)
                    medicineInsert.pharmacy_id = pharmacy_id
                    medicineInsert.pat_id = patient_id
                    medicineInsert.med_id = request.POST['id_of_med']
                    medicineInsert.number_of_pills = request.POST['num_of_pot']
                    medicineInsert.number_of_potions = request.POST['num_of_pil']
                    medicineInsert.save()

                    ##################### khan added from here to make notifications available ##################
                    # creating instance from table "AllNotification" to affect and get notification from it
                    notificationToBeSentToPatientFromPharmacy = AllNotification()
                    # taking ID from session of the doctor and patient I did't use what omar did because i need user instance
                    pharmacyIdInSession = request.session['pharmacy_id']
                    patientIdInSession = request.session['patien_id']
                    pharmacyId = organization.objects.get(org_id=pharmacyIdInSession)
                    patientId = patient.objects.get(Patient=patientIdInSession)
                    # affecting table "AllNotification" and save data to preview to the user
                    notificationToBeSentToPatientFromPharmacy.pharmacySenderId = pharmacyId
                    notificationToBeSentToPatientFromPharmacy.patientRecipient = patientId
                    notificationToBeSentToPatientFromPharmacy.message = 'Pharmacy ' + pharmacyId.org_name + ' is waiting for your review.'
                    notificationToBeSentToPatientFromPharmacy.save()
                    #############################################################################################
                # else:
                #     print('error')
                context = {
                    'DataNotSubmitted': medicineData,
                    'ph_id': pharmacy_id,
                }
                return render(request, 'patientMedicineToBeSubmit.html', context)

            else:
                return HttpResponseRedirect("/pharmacy/pharmacyPatientLogin/?notify=1")
        else:
            # return HttpResponseNotFound('<h1>patient not found</h1>')
            return HttpResponseRedirect("/pharmacy/pharmacyPatientLogin/?notify=2")
    else:
        return HttpResponseRedirect('/pharmacy/')



# def pharmacy_profile_view(request,pharid,hosid):
#     # pharmacyData = organization.objects.filter(Type=1).get(org_id=request.session['pharmacy_id'])
#     pharmacyData = organization.objects.filter(Type=1).get(org_id=pharid)
#     hospitaldata = hospital.objects.get(h_id=hosid)
#     context ={
#         'pharmacy': pharmacyData,
#         'ph_id':pharmacyData.org_id,
#         'hospital':hospitaldata,
#     }
#     return render(request, 'pharmacyProfileView.html',context)

# def pharmacy_profile_view(request):
#     id = request.session['pharmacy_id']
#     pharmacyData = organization.objects.filter(Type=1).get(org_id=id)
#     context ={
#         'pharmacy': pharmacyData,
#         'ph_id':pharmacyData.org_id,
#     }
#     return render(request, 'pharmacyProfileView.html',context)

def pharmacy_profile_view(request, pharid=None):
    pharmacyData = get_object_or_404(organization, org_id=pharid)
    context = {
        'pharmacy': pharmacyData,
        'ph_id': pharmacyData.org_id,
        'hos_id': None,
    }
    if 'patient_id' not in request.session and 'hospital_id' not in request.session and 'pharmacy_id' not in request.session:
        return HttpResponseRedirect('/pharmacy/')
    return render(request, 'pharmacyProfileView.html', context)

def pharmacyName(request):
    pharmacy_id = request.session['pharmacy_id']
    first_name = organization.objects.get(org_id=pharmacy_id).org_name
    return first_name

Implementation/EHR/ehr/templates/aboutUs.html
{% extends 'base.html' %}
{% load staticfiles %}
<!-- Info Boxes -->
{% block aboutUs %}

<div style="width:10px;height:175px"></div>
<div class="container">
    <div class="jumbotron" style="background-color:rgba(18,17,17,0.66);margin-top:30px;color: #FFF">
        <div class="row">
            <h2>About Project :</h2>
            <br>
            <b>The idea is about giving people the power of accessing their Health records from anywhere using the power of the Internet we started ( Electronic Health Record ) system by keeping patient's health records then analyzing it to predict if he will get a heart disease in the future using:
            <br>Python/Django framework to built the full web application
            <br>Data Mining models ( prediction models)
            <br>MySQL Data base </b>
        </div>
        <br>
        <div class="row">
            <h2>About Team :</h2>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <img src="{% static 'images/doctorManal.jpg'%}" alt="Avatar" style="width:300px; border-radius: 50%; height: 200px;">
                <b>Supervisor</b>
                <br>
                <b>Dr. Manal Abdelkader</b>
            </div>
            <div class="col-sm-4">
                <img src="{% static 'images/abdullah.jpg'%}" alt="Avatar" style="width:300px; border-radius: 50%; height: 200px;">
                <b>Abdullah Mohamed</b>
            </div>
            <div class="col-sm-4">
                <img src="{% static 'images/omarGamal.jpg'%}" alt="Avatar" style="width:300px; border-radius: 50%; height: 200px;">
                <b>Omar Gamal</b>
            </div>
        </div>
        <br>
        <br>
        <div class="row">
            <div class="col-sm-4">
                <img src="{% static 'images/mohamedAshraf.PNG'%}" alt="Avatar" style="width:300px; border-radius: 50%; height: 200px;">
                <b>Mohamed Ashraf</b>
            </div>
            <div class="col-sm-4">
                <img src="{% static 'images/noran.jpg'%}" alt="Avatar" style="width:300px; border-radius: 50%; height: 200px;">
                <b>Noran Yahia</b>
            </div>
            <div class="col-sm-4">
                <img src="{% static 'images/Teha.jpg'%}" alt="Avatar" style="width:300px; border-radius: 50%; height: 200px;">
                <b>Abdulfatah Ramadan</b>
            </div>
        </div>
    </div>
</div>
{% endblock aboutUs %}

Implementation/EHR/ehr/templates/forgetPassword.html
{% extends "base.html"%}
{% load staticfiles %}
{% block forgetPassword %}

<div style="width:10px;height:175px"></div>
<div class="container">
    <h2 style="text-align:center;color:#FFF;margin:20px 0px 30px 0px">Reset Account Password</h2>
    <div class="jumbotron" style="background-color:rgba(18,17,17,0.66)">
        <form method="POST" action="">
            {% csrf_token %}
            <div class="row">
                <div class="col-4">
                    <div class="row">
                        <div style="width:200px;margin: auto">
                            {% if user %}
                                <img src="{{ user.Profile_picture }}" alt="profile picture" class="img-thumbnail"/>
                            {% endif %}
                        </div>
                    </div>
                    <div class="row" style="text-align: center;;margin-top: 10px">
                        <div class="col-sm">
                            <label style="color: #FFF;">{{ user.first_name|upper }} {{ user.middle_name|upper }} {{ user.last_name|upper }}</label>
                        </div>
                    </div>
                </div>
                <div class="col-8">
                    <div class="form-row" style="margin-bottom:20px">
                        <div class="col-sm">
                            <input type="hidden" name="userid" value="{{ user.user_id }}">
                            <input type="password" name="old_pass" class="form-control" placeholder="Old Password" required="">
                        </div>
                    </div>
                    <div class="form-row" style="margin-bottom:20px">
                        <div class="col-sm">
                            <input type="password" id="pass" name="new_pass" class="form-control" placeholder="New Password" required="">
                            <b id="warn1" class="hide">
                                <i class="fa fa-warning" aria-hidden="true"></i>
                                Not Matched
                            </b>
                        </div>
                    </div>
                    <div class="form-row" style="margin-bottom:20px">
                        <div class="col-sm">
                            <input type="password" id="re_pass" name="confirm_pass" class="form-control" placeholder="Confirm Password" required="">
                            <b id="warn2" class="hide">
                                <i class="fa fa-warning" aria-hidden="true"></i>
                                Not Matched
                            </b>
                        </div>
                    </div>
                    <div class="form-row" style="margin-bottom:20px">
                        <div class="col-sm" style="text-align: center">
                            <button id="id_signup_submit" type="submit" style="border-radius: 50px;width:30%;margin:auto" class="button home_button">Submit</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock forgetPassword %}

Implementation/EHR/ehr/templates/hospital_charts.html
{% include "base.html" %}
{% block javascript %}
    <script
            src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>

    <script>
{% endblock javascript %}


{% block jquery %}
    var endpoint = '{%url "doctor:api-data"%}'
    var defulatdata1 = []
    var labels1 = []
    var defulatdata2 = []
    var labels2 = []
    var defulatdata3 = []
    var labels3 = []
    $.ajax({
        method: "GET",
        url: endpoint,
        success: function (data) {
            labels1 = data.data1.label
            defulatdata1 = data.data1.default
            labels2 = data.data2.label
            defulatdata2 = data.data2.default
            labels3 = data.data3.label
            defulatdata3 = data.data3.default
            BarChart1()
            Barchart2()
            H_barchart()
            console.log(1000)
        },

        error: function (error_data) {
            console.log("error");
            console.log(error_data);

        }
    })

    function BarChart1() {
        var ctx = document.getElementById('1').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: labels1,
                datasets: [{
                    label: '# of Votes',
                    data: defulatdata1,
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        })
    }
    function Barchart2() {
        var ctx = document.getElementById('2').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: labels2,
                datasets: [{
                    label: '# of Votes',
                    data: defulatdata2,
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        })
    }
    function H_barchart() {
        var ctx = document.getElementById('3').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'horizontalBar',
            data: {
                labels: labels3,
                datasets: [{
                    label: '# of Votes',
                    data: defulatdata3,
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        })
    }
{% endblock %}
</script>
{% block home_content %}

    <div style="width:10px;height:175px"></div>
    <div class="container">
        <div class="jumbotron">
            <div class='row'>
                <div class='col-sm-4'>
                    <h1>Stat1</h1>
                    <canvas id="1" width="400" height="400"></canvas>
                </div>
                <div class='col-sm-4'>
                    <h1>Stat2</h1>
                    <canvas id="2" width="400" height="400"></canvas>
                </div>
                <div class='col-sm-4'>
                    <h1>Stat3</h1>
                    <canvas id="3" width="400" height="400"></canvas>
                </div>
            </div>

        </div>
    </div>

{% endblock home_content %}

Implementation/EHR/ehr/templates/labIndex.html
{% extends 'base.html' %}
{% block labIndex %}

    {% if request.GET.notify == "patient_not_found" %}
        <script>
            alert("This's not a patient")
        </script>
    {% elif request.GET.notify == "user_not_found" %}
        <script>
            alert("This's not a user")
        </script>
    {% elif request.GET.notify == "0" %}
        <script>
            alert("No Patient With This ID")
        </script>
    {% elif request.GET.notify == "1" %}
        <script>
            alert("You Don't Have Any Analytics")
        </script>
    {% elif request.GET.notify == "2" %}
        <script>
            alert("You Don't Have Any Rays")
        </script>
    {% endif %}
    <div class="home_container" style="top:30%">
        <div class="container">
            <div class="row">
                <div class="col-sm">
                    <div class="home_content">
                        <div class="home_title">Patient Login</div>
                        <form method="POST" action="">
                            {% csrf_token %}
                            <div class="home_text">
                                <div class="form-group">
                                    <input type="text" class="form-control" name="pat_id" aria-describedby="emailHelp"
                                           placeholder="Enter Patient ID" required="required" value="{{ SSN_ID }}">
                                </div>
                                <div class="form-group">
                                    <select class="form-control" style="height: auto" name="type" required>
                                        <option value="" selected disabled>Choose type...</option>
                                        <option value="1">Analytics</option>
                                        <option value="2">Rays</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="button home_button" name="BtnForSearch">Search</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="home_text">
                <div class="row">
                    <div class="col-sm-3" style="margin-top: 45px">
                        <span>Login Fast</span>
                    </div>
                    <div class="col-sm-3">
                        <a href="{% url 'lab:QRCodeScanView' %}">
                            <button type="button" class="button home_button" name="btnForScanQR">Scan Id</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock labIndex %}

Implementation/EHR/ehr/templates/patientAnalyticsToBeSubmit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block patientAnalyticsList %}


<div style="width:10px;height:175px"></div>
<div class="container">
    <h2 style="text-align:center;color:#FFF;margin:20px 0px 30px 0px">Perform Analytics</h2>
    <div class="jumbotron" style="background-color:rgba(18,17,17,0.66); font-size: 22px;padding: 2rem 2rem;overflow: auto;height: 650px;">
        {% if AnalyticsNotSubmitted %}
            {% for data in AnalyticsNotSubmitted %}
                <form method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row" style="border:solid 5px #32c69a;border-radius: 10px;margin-bottom: 5px">
                        <div class="col-sm-10" style="text-align: center">
                            <div class="row">
                                <div class="col-sm-6">
                                    Analytics Name
                                </div>
                                <div class="col-sm-6">
                                    Analytics Result
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6" style="color: #FFF">
                                    {{ data.analy.analytics_name }}
                                </div>
                                <div class="col-sm-6">
                                    <input type="file" class="inputfile" id="file1" name="analytics_result" required="required">
                                    <label for="file1" style="margin-bottom: 10px;font-size: 20px;width: 60%;background-color: #28a745;">Upload</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-2" style="margin: auto;text-align: center">
                            <input type="hidden" name="ana_id" value="{{ data.P_A_id }}">
                            <input type="hidden" name="analy_id" value="{{ data.analy.analytics_id }}">
                            <BUTTON class="btn btn-success" style="font-size: 22px" type="submit">Submit</BUTTON>
                        </div>
                    </div>
                </form>
            {% endfor %}
        {% else %}
            <h1 style="text-align: center">You Have no Analytics</h1>
        {% endif %}
    </div>
</div>
{% endblock patientAnalyticsList %}