Implementation/EHR/ehr/doctor/urls.py
from django.conf.urls import url
from doctor import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'doctor'
urlpatterns = [
    url(r'^Home/$', views.Doctor, name='doctor'),
    url(r'^resetpassword/$', views.RestDoctorPassword,name='resetpassword'),
    url(r'^$',views.GetPatianTID , name='patiant_id'),
    url(r'^patiant/prescription/$',views.ReportListView.as_view() , name='prescriptionlist'),
    url(r'^doctorProfileView/(?P<pk>[-\w]+)/$',views.doctorProfileDetialView.as_view(), name='doctorProfileView'),
    url(r'^patiant/prescription/(?P<pk>[-\w]+)/$',views.PrescriptionDetialView.as_view() , name='prescriptiondetial'),
    url(r'^prescription/newcreate/$',views.prescriptionFormView.as_view(),name='presc_create'),
    url(r'^prescription/update/(?P<pk>[-\w]+)/$',views.prescriptionUpdate.as_view(),name='update'),

    url(r'^patiant/prescription/(?P<pk>[-\w]+)/medecines/$',views.Medicen_List.as_view(),name='medlist'),
    url(r'^patiant/prescription/medecines/(?P<pk>[-\w]+)/$',views.Medicin_DetialView.as_view(),name='meddital'),
    url(r'^patiant/prescription/medecines/update/(?P<pk>[-\w]+)/$' , views.Medicen_UPDATE.as_view(),name='medupdate'),
    url(r'^patiant/prescription/medecines/newcreate/(?P<pk>[-\w]+)/$',views.MedicenFormView.as_view(),name='newmed'),

    url(r'^patiant/prescription/(?P<pk>[-\w]+)/rays/$',views.rays_List.as_view(),name='rayslist'),
    url(r'^patiant/prescription/rays/(?P<pk>[-\w]+)/$',views.rays_DetialView.as_view(),name='raydetial'),
    url(r'^patiant/prescription/rays/update/(?P<pk>[-\w]+)/$' , views.rays_UPDATE.as_view(),name='raysupdate'),
    url(r'^patiant/prescription/rays/newcreate/(?P<pk>[-\w]+)/$',views.raysFormView.as_view(),name='newray'),

    url(r'^patiant/prescription/(?P<pk>[-\w]+)/analytics/$',views.analytics_List.as_view(),name='analyticslist'),
    url(r'^patiant/prescription/analytics/(?P<pk>[-\w]+)/$',views.analytics_DetialView.as_view(),name='analyticsdetial'),
    url(r'^patiant/prescription/analytics/update/(?P<pk>[-\w]+)/$' , views.analytics_UPDATE.as_view(),name='analyticssupdate'),
    url(r'^patiant/prescription/analytics/newcreate/(?P<pk>[-\w]+)/$',views.analyticsFormView.as_view(),name='newanalytics'),

    # url(r'^doctorProfileView/$', views.doctor_profile_view, name='doctor_profile_view'),
    # url(r'^doctorProfileView/(?P<docid>\w+)/$', views.doctor_profile_view,name='doctor_profile_view'),
    url(r'^QRScan/$', views.QRCodeScanView, name='QRCodeScanView'),
    # url(r'^medi/$', views.medi, name='medi'),
    url(r'^QRScan/$', views.QRCodeScanView, name='QRCodeScanView'),
    url(r'^api/charts/data/$', views.DoctorStatistics.as_view(),name="api-data"),
    url(r'^Statistics/$', views.StatView.as_view(),name="stat"),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Implementation/EHR/ehr/ehr/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from patient import views

urlpatterns = [
    url(r'^$', views.patientLogin, name='patientLogin'),
    url(r'^catalog/$', views.patientLogin, name='patientLogin'),
    url(r'^admin/', admin.site.urls),
    url(r'^doctor/', include('doctor.urls')),
    url(r'^patient/', include('patient.urls')),
    url(r'^hospital/', include('hospital.urls')),
    url(r'^clinic/', include('clinic.urls')),
    url(r'^predict/',include('predict_risk.urls')),
    path('pharmacy/', include('pharmacy.urls')),
    path('lab/', include('lab.urls')),
]

admin.site.site_header = "EHR ADMIN"
admin.site.site_title = "EHR ADMIN"
admin.site.index_title = "Welcome to EHR SYSTEM"

Implementation/EHR/ehr/hospital/urls.py
from django.conf.urls import url
from hospital import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'hospital'

urlpatterns = [
    url(r'^$', views.hospitalLogin, name='hospitalLogin'),
    url(r'^Logout$', views.hospitalLogout, name='hospitalLogout'),
    url(r'^Index/$', views.Index, name='Index'),
    url(r'^AddHospitalDoctor/$', views.add_doctor, name='add_doctor'),
    url(r'^updateHospitalDoctor/(?P<Docid>\w+)/$', views.update_doctor, name='update_doctor'),
    url(r'^updatePharmacy/(?P<pharid>\w+)/(?P<hosid>\w+)/$', views.update_pharmacy, name='update_pharmacy'),
    url(r'^updateLab/(?P<labid>\w+)/(?P<hosid>\w+)/$', views.update_lab, name='update_lab'),
    url(r'^resetHospitalDoctorPassowrd/(?P<id>\w+)/$', views.reset_doc_passowrd, name='reset_doc_passowrd'),
    url(r'^AddPharmacy/$', views.add_pharmacy, name='add_pharmacy'),
    url(r'^AddLab/$', views.add_Lab, name='add_Lab'),
    url(r'^hospitalProfileView/(?P<hosid>\w+)/$', views.hospital_profile_view, name='hospital_profile_view'),
    url(r'^DeleteHospitalDoctor/(?P<Did>\w+)/$', views.delete_doctor, name='delete_doctor'),
    url(r'^DeletePharmayLab/(?P<ph_lb_id>\w+)/(?P<ph_lb_type>\w+)$', views.delete_pharmacy_lab, name='delete_pharmacy_lab'),
    url(r'^UnblockHospitalDoctor/(?P<ssn>\w+)/$', views.unblock_doctor, name='unblock_doctor'),

    # url(r'^api/charts/data/$', views.HospitalStatistics.as_view(),name="api-data"),
    # url(r'^Statistics/$', views.StatView.as_view(),name="stat"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Implementation/EHR/ehr/lab/urls.py
from django.conf.urls import url
from django.urls import path
from lab import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'lab'

urlpatterns = [
    path('', views.labLogin, name='labLogin'),
    path('logout/', views.labLogout, name='labLogout'),
    path('labPatientLogin/', views.labPatientLogin, name='labPatientLogin'),
    path('labPatientLogin/Analytics/', views.AnalyticsListView, name='AnalyticsListView'),
    path('labPatientLogin/Rays/', views.RaysListView, name='RaysListView'),
    url(r'^labProfileView/(?P<labid>\w+)/$', views.lab_profile_view,name='lab_profile_view'),
    url(r'^QRScan/$', views.QRCodeScanView, name='QRCodeScanView'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Implementation/EHR/ehr/patient/urls.py
from django.conf.urls import url
from django.urls import path

from patient import views as view
from django.conf import settings
from django.conf.urls.static import static

app_name = 'patient'

urlpatterns = [
    path('', view.patientLogin, name='patientLogin'),
    url(r'^Index/$', view.home, name='home'),
    url(r'^logout/$', view.patientLogout, name='logout'),
    url(r'^patientProfile/$', view.patient_profile, name='patient_profile'),
    url(r'^patientProfileUpdate/$', view.patient_profile_update, name='patient_profile_update'),
    # url(r'^patientProfileView/$', view.patient_profile_view, name='patient_profile_view'),
    url(r'^patientProfileView/(?P<pk>[-\w]+)/$',view.patientProfileDetialView.as_view(), name='patientProfileView'),
    url(r'^signup/$', view.temp_Register, name='signup'),
    url(r'^ajax/validate_email/$', view.validate_email, name='validate_email'),
    url(r'^profile/valid_email/$', view.valid_email, name='valid_email'),
    url(r'^patientHistory/$', view.patientHistory, name='patientHistory'),
    # url(r'^patientCard/$', view.patientCard, name='patientCard'),
    url(r'^patientCard/(?P<userid>[-\w]+)/$', view.patientCard, name='patientCard'),
    url(r'^patientDoctor/$', view.patientDoctor, name='patientDoctor'),
    url(r'^QRScan/$', view.QRCodeScanView, name='QRCodeScanView'),
    url(r'^forgetPassword/(?P<uid>[-\w]+)/$', view.forget_password, name='forget_password'),
    # url(r'^Notification',view.Notification, name='notification'),
    url(r'^DoctorRate/(?P<userid>[-\w]+)/(?P<patid>[-\w]+)/(?P<hosid>[-\w]+)/',view.doctorRate, name='doctorRate'),
    url(r'^OrganizationRate/(?P<orgid>[-\w]+)/(?P<patid>[-\w]+)/',view.organizationRate, name='organizationRate'),
    url(r'^aboutUs/$',view.aboutUs, name='aboutUs'),

    url(r'^getReport/(?P<report_id>\w+)/$', view.getReport, name='getReport'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Implementation/EHR/ehr/templates/Doctor_app/multi_analytics_list.html
{% extends 'Doctor_app/Doctor_base.html' %}
{% block home_content %}

{#<div class="info">#}
{#    <div class="container">#}
{#        <div class="row row-eq-height">#}
{#          <ol>#}
{#            {% for m in analytics %}#}
{#            <h2><li>rays : <a href="{% url 'doctor:analyticsdetial' pk=m.P_A_id%}">{{m.P_A.analy.analytics_name}}</a></li></h2>#}
{#            <p {% if forloop.last %}><a  class="btn btn-primary"href="{% url 'doctor:newanalytics' pk=m.report.prescription.prescription_id%}">CreateAnalytics{% endif %}</a></p>#}
{#            <p {% if forloop.last %}><a  class="btn btn-primary"href="{% url 'doctor:newray' pk=m.report.prescription.prescription_id%}">Create Rays{% endif %}</a></p>#}
{#            <p {% if forloop.last %}><a  class="btn btn-primary"href="{% url 'doctor:newmed' pk=m.report.prescription.prescription_id%}">Create Medicins{% endif %}</a></p>#}
{#            <p {% if forloop.last %}><a class="btn btn-primary" href="{% url 'doctor:prescriptiondetial' pk=m.report.prescription.prescription_id%}">Prescription {% endif %}</a></p>#}
{#            {%endfor%}#}
{##}
{#          </ol>#}
{#        </div>#}
{#    </div>#}
{#</div>#}

<div style="width:10px;height:175px"></div>
<div class="container">
    <div class="jumbotron" style="background-color:rgba(18,17,17,0.66);margin-top:30px;color: #FFF">
        <div class="row" style="border-bottom: solid 5px #32c69a">
            <div class="col-sm" style="text-align: center">
                <a href="{% url 'doctor:prescriptiondetial' pk=request.session.presc_id%}">
                    <button type="submit" style="margin-top:10px;font-size: 18px;border-radius: 50px;" class="button home_button">Prescriptions</button>
                </a>
            </div>
            <div class="col-sm" style="text-align: center">
                <a href="{% url 'doctor:newanalytics' pk=request.session.presc_id%}">
                    <button type="submit" style="margin-top:10px;font-size: 18px;border-radius: 50px;" class="button home_button">Create Analytics</button>
                </a>
            </div>
            <div class="col-sm" style="text-align: center">
                <a href="{% url 'doctor:newray' pk=request.session.presc_id%}">
                    <button type="submit" style="margin-top:10px;font-size: 18px;border-radius: 50px;" class="button home_button">Create Rays</button>
                </a>
            </div>
            <div class="col-sm" style="text-align: center">
                <a href="{% url 'doctor:newmed' pk=request.session.presc_id%}">
                    <button type="submit" style="margin-top:10px;font-size: 18px;border-radius: 50px;" class="button home_button">Create Medicines</button>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm" style="text-align: center">
                <label style="font-size: 30px;font-weight: bold;margin: 10px;border-bottom: solid 5px #32c69a;">Analytics Details</label>
            </div>
        </div>
        <div class="row" style="overflow: auto;height: 300px">
            <div class="col-sm" style="text-align: center;font-size: 20px">
                {% for m in analytics reversed%}
                    <div class="row" style="margin-top: 20px;border-bottom: solid 2px #32c69a;padding-bottom: 5px;">
                        <div class="col-sm">
                            Name
                        </div>
                        <div class="col-sm">
                            {{m.P_A.analy.analytics_name}}
                        </div>
                        <div class="col-sm">
                            Result
                        </div>
                        <div class="col-sm">
                            {% if m.P_A.analytics_result %}
                                <a href="{{m.P_A.analytics_result}}">Link</a>
                            {% else %}
                                No Result Yet
                            {% endif %}
                        </div>
{#                        <div class="col-sm" style="text-align: center">#}
{#                            <a href="{% url 'doctor:analyticssupdate' pk=m.P_A_id %}">#}
{#                                <button type="submit" style="color: #FFF;background-color: #32c69a;font-size: 18px;border-radius: 50px;" class="btn">Edit</button>#}
{#                            </a>#}
{#                        </div>#}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock home_content %}

Implementation/EHR/ehr/templates/Doctor_app/multi_rays_list.html
{% extends 'Doctor_app/Doctor_base.html' %}
{% block home_content %}

{#<div class="info">#}
{#    <div class="container">#}
{#        <div class="row row-eq-height">#}
{#          <ol>#}
{#            {% for m in rays %}#}
{#            <h2><li>rays : <a href="{% url 'doctor:raydetial' pk=m.P_R_id%}">{{m.P_R.ray.ray_name}}</a></li></h2>#}
{#            <p {% if forloop.last %}><a  class="btn btn-primary"href="{% url 'doctor:newanalytics' pk=m.report.prescription.prescription_id%}">CreateAnalytics{% endif %}</a></p>#}
{#            <p {% if forloop.last %}><a  class="btn btn-primary"href="{% url 'doctor:newray' pk=m.report.prescription.prescription_id%}">Create Rays{% endif %}</a></p>#}
{#            <p {% if forloop.last %}><a  class="btn btn-primary"href="{% url 'doctor:newmed' pk=m.report.prescription.prescription_id%}">Create Medicins{% endif %}</a></p>#}
{#            <p {% if forloop.last %}><a class="btn btn-primary" href="{% url 'doctor:prescriptiondetial' pk=m.report.prescription.prescription_id%}">Prescription {% endif %}</a></p>#}
{#            {%endfor%}#}
{#            <p><a class="btn btn-primary" href="{% url 'doctor:prescriptionlist'%}">Prescription List</a></p>#}
{#          </ol>#}
{#        </div>#}
{#    </div>#}
{#</div>#}


<div style="width:10px;height:175px"></div>
<div class="container">
    <div class="jumbotron" style="background-color:rgba(18,17,17,0.66);margin-top:30px;color: #FFF">
        <div class="row" style="border-bottom: solid 5px #32c69a">
            <div class="col-sm" style="text-align: center">
                <a href="{% url 'doctor:prescriptiondetial' pk=request.session.presc_id%}">
                    <button type="submit" style="margin-top:10px;font-size: 18px;border-radius: 50px;" class="button home_button">Prescriptions</button>
                </a>
            </div>
            <div class="col-sm" style="text-align: center">
                <a href="{% url 'doctor:newanalytics' pk=request.session.presc_id%}">
                    <button type="submit" style="margin-top:10px;font-size: 18px;border-radius: 50px;" class="button home_button">Create Analytics</button>
                </a>
            </div>
            <div class="col-sm" style="text-align: center">
                <a href="{% url 'doctor:newray' pk=request.session.presc_id%}">
                    <button type="submit" style="margin-top:10px;font-size: 18px;border-radius: 50px;" class="button home_button">Create Rays</button>
                </a>
            </div>
            <div class="col-sm" style="text-align: center">
                <a href="{% url 'doctor:newmed' pk=request.session.presc_id%}">
                    <button type="submit" style="margin-top:10px;font-size: 18px;border-radius: 50px;" class="button home_button">Create Medicines</button>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm" style="text-align: center">
                <label style="font-size: 30px;font-weight: bold;margin: 10px;border-bottom: solid 5px #32c69a;">Analytics Details</label>
            </div>
        </div>
        <div class="row" style="overflow: auto;height: 300px">
            <div class="col-sm" style="text-align: center;font-size: 20px">
                {% for m in rays reversed%}
                    <div class="row" style="margin-top: 20px;border-bottom: solid 2px #32c69a;padding-bottom: 5px;">
                        <div class="col-sm">
                            Name
                        </div>
                        <div class="col-sm">
                            {{m.P_R.ray.ray_name}}
                        </div>
                        <div class="col-sm">
                            Result
                        </div>
                        <div class="col-sm">
                            {% if m.P_R.rays_result %}
                                <a href="{{m.P_R.rays_result}}">Link</a>
                            {% else %}
                                No Result Yet
                            {% endif %}
                        </div>
{#                        <div class="col-sm" style="text-align: center">#}
{#                            <a href="{% url 'doctor:raysupdate' pk=m.P_R_id %}">#}
{#                                <button type="submit" style="color: #FFF;background-color: #32c69a;font-size: 18px;border-radius: 50px;" class="btn">Edit</button>#}
{#                            </a>#}
{#                        </div>#}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock home_content %}

Implementation/EHR/ehr/templates/Doctor_app/navbar.html
{% load staticfiles %}
<!-- Menu -->
<div class="menu trans_500">
    <div class="menu_content d-flex flex-column align-items-center justify-content-center text-center">
        <div class="menu_close_container"><div class="menu_close"></div></div>
        <form action="#" class="menu_search_form">
            <input type="text" class="menu_search_input" placeholder="Search" required="required">
            <button class="menu_search_button"><i class="fa fa-search" aria-hidden="true"></i></button>
        </form>
        <ul>
            <li class="menu_item"><a href="/">Home</a></li>
            <li class="menu_item"><a href="#">About us</a></li>
            <li class="menu_item"><a href="#">Services</a></li>
            <li class="menu_item"><a href="{% url 'patient:patientLogin' %}">Login</a></li>
            <li class="menu_item"><a href="{% url 'patient:signup' %}">Register</a></li>
        </ul>
    </div>
    <div class="menu_social">
        <ul>
            <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
        </ul>
    </div>
</div>

<!-- Home -->
<div class="
    {% if request.get_full_path == '/patient/patientHistory/' %} home_2
    {% else %} home
    {% endif %}
    "style="
    {% if request.get_full_path == '/patient/Index/' %} height:170px;
    {% elif request.get_full_path == '/hospital/Index/' %} height:170px;
    {% elif request.get_full_path == '/patient/patientProfile/' %} height:950px;
    {% elif request.get_full_path == '/patient/patientProfileView/' %} height:0px;
    {% elif request.get_full_path == '/hospital/AddDoctor/' %} height:0px;
    {% elif request.get_full_path == '/hospital/AddPharmacy/' %} height:0px;
    {% elif request.get_full_path == '/hospital/AddLab/' %} height:0px;
    {% elif request.get_full_path == '/hospital/hospitalProfileView/' %} height:0px;
    {% elif request.get_full_path == '/patient/patientCard/' %} height:0px;
    {% elif '/doctor/doctorProfileView/' in request.get_full_path %} height:0px;
    {% endif %}">
    <div class="
    {% if request.get_full_path == '/patient/patientHistory/' %}
    {% else %} background_image
    {% endif %}
    " style="
    {% if request.get_full_path == '/patient/patientProfile/' %} height:120%;
    {% elif request.get_full_path == '/patient/patientProfile/?c=1' %} height:120%;
    {% elif request.get_full_path == '/patient/Index/' %} display:none;
    {% elif request.get_full_path == '/hospital/Index/' %} display:none;
    {% elif request.get_full_path == '/hospital/AddDoctor/' %} display:none;
    {% elif request.get_full_path == '/hospital/AddPharmacy/' %} display:none;
    {% elif request.get_full_path == '/hospital/AddLab/' %} display:none;
    {% elif request.get_full_path == '/hospital/hospitalProfileView/' %} display:none;
    {% elif request.get_full_path == '/patient/patientProfileView/' %} display:none;
    {% elif request.get_full_path == '/patient/patientCard/' %} display:none;
    {% elif '/doctor/doctorProfileView/' in request.get_full_path %} display:none;
    {% endif %}
    "></div>

    <!-- Header -->
    <header class="header" id="header">
        <div>
            <div class="header_top">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="header_top_content d-flex flex-row align-items-center justify-content-start">
                                <div class="logo">
                                    <a href="#">EHR<span>|</span>HealthCare</a>
                                </div>
                                <div class="header_top_extra d-flex flex-row align-items-center justify-content-start ml-auto">
                                    <div class="header_top_nav">
                                        <ul class="d-flex flex-row align-items-center justify-content-start">
                                            <li><a href="about.html">About Us</a></li>
                                            <li><a href="services.html">Services</a></li>
                                        </ul>
                                    </div>
                                    <div class="header_top_phone">
                                        <i class="fa fa-phone" aria-hidden="true"></i>
                                        <span>+02 012 3456 7890</span>
                                    </div>
                                </div>
                                <div class="hamburger ml-auto"><i class="fa fa-bars" aria-hidden="true"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="header_nav" id="header_nav_pin">
                <div class="header_nav_inner">
                    <div class="header_nav_container">
                        <div class="container">
                            <div class="row">
                                <div class="col">
                                    <div class="header_nav_content d-flex flex-row align-items-center justify-content-start">
                                        <nav class="main_nav">
                                            <ul class="d-flex flex-row align-items-center justify-content-start">
                                                {% if 'patient_id' not in request.session and 'doctor_id' not in request.session and 'hospital_id' not in request.session and 'pharmacy_id' not in request.session and 'lab_id' not in request.session %}
                                                {% elif 'patient_id' in request.session %}
                                                    <li><a href="{% url 'patient:home'%}">Home</a></li>
                                                {% elif 'doctor_id' in request.session %}
                                                    <li><a href="{% url 'doctor:patiant_id'%}">Home</a></li>
                                                {% elif 'hospital_id' in request.session %}
                                                    <li><a href="{% url 'hospital:Index'%}">Home</a></li>
                                                {% elif 'pharmacy_id' in request.session %}
                                                    <li><a href="{% url 'pharmacy:pharmacyPatientLogin'%}">Home</a></li>
                                                {% elif 'lab_id' in request.session %}
                                                    <li><a href="{% url 'lab:labPatientLogin'%}">Home</a></li>
                                                {% endif %}
                                                {% if 'patient_id' not in request.session and 'doctor_id' not in request.session and 'hospital_id' not in request.session and 'pharmacy_id' not in request.session and 'lab_id' not in request.session %}
                                                    {% if 'type' in request.session %}
                                                    {% else%}
                                                        <li><a href="{% url 'patient:patientLogin'%}">Login</a></li>
                                                        <li><a href="{% url 'patient:signup'%}">Register</a></li>
                                                    {% endif %}
                                                {% endif %}
                                                {% if 'patient_id' in request.session %}
                                                    <li><a href="{% url 'patient:patientHistory'%}">History</a></li>
                                                    <li><a href="{% url 'patient:patient_profile_view'%}">Profile</a></li>
                                                    <li><a href="{% url 'patient:logout'%}">Logout</a></li>
                                                {% elif 'doctor_id' in request.session %}
                                                    <li><a href="{% url 'doctor:patiant_id'%}">Enter A Patiant</a></li>
                                                    <li><a href="{% url 'doctor:doctor_profile_view' %}">Profile</a></li>
                                                    <li><a href="{% url 'patient:logout' %}">Logout</a></li>
                                                {% elif 'hospital_id' in request.session %}
                                                    <li><a href="{% url 'hospital:hospital_profile_view' %}">Profile</a></li>
                                                    <li><a href="{% url 'hospital:hospitalLogout'%}">Logout</a></li>
                                                {% elif 'pharmacy_id' in request.session %}
                                                    <li><a href="#">Profile</a></li>
                                                    <li><a href="{% url 'pharmacy:pharmacyLogout'%}">Logout</a></li>
                                                {% elif 'lab_id' in request.session %}
                                                    <li><a href="#">Profile</a></li>
                                                    <li><a href="{% url 'lab:labLogout' %}">Logout</a></li>
                                                {% endif %}
                                            </ul>
                                        </nav>
                                        <div class="search_content d-flex flex-row align-items-center justify-content-end ml-auto">
                                            <form action="#" id="search_container_form" class="search_container_form">
                                                <input type="text" class="search_container_input" placeholder="Search" required="required">
                                                <button class="search_container_button"><i class="fa fa-search" aria-hidden="true"></i></button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

Implementation/EHR/ehr/templates/Doctor_app/patient_medicine_detail.html
{% extends 'Doctor_app/Doctor_base.html' %}
{% block home_content %}

{#<div class="info">#}
{#    <div class="container">#}
{#        <div class="row row-eq-height">#}
{#          <ol>#}
{#            <ol>#}
{#              {%if med_p_detial%}#}
{#              <h2><li>{{med_p_detial.med.medicine_name}}</li></h2>#}
{#              <h2><li>{{med_p_detial.number_of_potions}}</li></h2>#}
{#              <h2><li>{{med_p_detial.number_of_pills}}</li></h2>#}
{#              <p><a class="btn btn-warning" href="{% url 'doctor:medupdate' pk=med_p_detial.P_M_id%}">Update</a></p>#}
{##}
{#              {%endif%}#}
{#              <p><a class="btn btn-warning" href="{% url 'doctor:newmed' pk=med_p_detial.report.prescription.prescription_id%}">Create CreateMediciene</a></p>#}
{#          </ol>#}
{#          </ol>#}
{##}
{#        </div>#}
{#    </div>#}
{#</div>#}



{% endblock home_content %}